WD-2205 Add Kubeflow beta 1.7 banner
canonical/charmhub.io pull request #1529
Opened 2023-03-01 09:33 UTC by carkod

## Done

Sites tribe [got a request](https://docs.google.com/document/d/19_9cUiyjxWXPvLaZc0_DOglsCQwlJFW8gET7sZt7IYI/edit#) to add this Kubeflow 1.7 beta banner

This banner is scheduled to be up on 8th of March and be taken down on 22nd of March (check the brief linked previously).

I've also fixed your dotrun issue, I think it just needs some time to be able to `curl`, dotrun is probably doing stuff

## How to QA

- Navigate to https://charmhub-io-1529.demos.haus/kubeflow
- Click on the links.

## Issue / Card
Fixes https://warthogs.atlassian.net/browse/WD-2205?atlOrigin=eyJpIjoiNGMzNjRhODYxZDY5NDFhMzhlMDllMzExMzE0MzRjODgiLCJwIjoiaiJ9

## Screenshots

![image](https://user-images.githubusercontent.com/14939793/222092958-a5d0edd1-bc01-4eee-aad9-9341f8767f49.png)

2023-03-01 09:33 UTC, webteam-app commented
Demo starting at https://charmhub-io-1529.demos.haus

2023-03-01 10:28 UTC, Lukewh requested changes

2023-03-01 10:28 UTC, Lukewh commented on webapp/app.py
> +def utility_processor():
Can you move these into `handlers.py`, where `utility_processor` is already defined? I'd like to keep `app.py` as clean as possible, thanks.

2023-03-01 10:30 UTC, Lukewh commented
If I click on the "configure" tab, the banner disappears, should it be on all kubeflow pages?

2023-03-01 10:33 UTC, Lukewh commented
Please don't merge this, I want to talk to Andreea to make sure this is the right solution to what they're trying to achieve

2023-03-01 10:45 UTC, carkod commented
> Please don't merge this, I want to talk to Andreea to make sure this is the right solution to what they're trying to achieve

Good point. I can also make it work with whatever starts with "kubeflow". Let me know

2023-03-02 10:38 UTC, Lukewh approved these changes
:+1: LGTM

2023-03-02 10:39 UTC, Lukewh commented
@carkod thanks for updating, and this looks good now - you can change the start date and get it merged, thanks :)

2023-03-02 13:22 UTC, carkod commented
> @carkod thanks for updating, and this looks good now - you can change the start date and get it merged, thanks :)

Thanks. I assume you got confirmation that they want it displayed in all /kubeflow/<path> pages?

2023-03-02 14:12 UTC, Lukewh commented
I see you're still working on this, let me know when to review again

2023-03-02 14:15 UTC, carkod commented
> I see you're still working on this, let me know when to review again

Sorry, I'm just trying to fix the dotrun issue. It started failing again, but I can see what the problem is. It's doing the `curl` and then failing, but after a while the assets are built...

Also it looks a bit weird to me, that you have dotrun as required but run-image is not required? I assume you don't `docker run` your PRs, so it'd be good to have this check as required, because if that's broken, very likely prod or staging would be broken.

2023-03-02 14:17 UTC, Lukewh commented
> > I see you're still working on this, let me know when to review again
> 
> Sorry, I'm just trying to fix the dotrun issue. It started failing again, but I can see what the problem is. It's doing the `curl` and then failing, but after a while the assets are built...
> 
> Also it looks a bit weird to me, that you have dotrun as required but run-image is not required? I assume you don't `docker run` your PRs, so it'd be good to have this check as required, because if that's broken, very likely prod or staging would be broken.
> 
> But anyway, it's not work of this specific feature, I could leave it for another PR

Yeah, if things work without the changes to dotrun, move them to another PR

2023-03-02 14:21 UTC, carkod commented
> > > I see you're still working on this, let me know when to review again
> > 
> > 
> > Sorry, I'm just trying to fix the dotrun issue. It started failing again, but I can see what the problem is. It's doing the `curl` and then failing, but after a while the assets are built...
> > Also it looks a bit weird to me, that you have dotrun as required but run-image is not required? I assume you don't `docker run` your PRs, so it'd be good to have this check as required, because if that's broken, very likely prod or staging would be broken.
> > But anyway, it's not work of this specific feature, I could leave it for another PR
> 
> Yeah, if things work without the changes to dotrun, move them to another PR

Ok, seems like it worked!

Everything else is the same, I just changed the `pr.yaml` command

2023-03-02 14:22 UTC, Lukewh approved these changes
:+1: LGTM

2023-03-02 14:24 UTC, merged